### PR TITLE
Proof of unsigned/signed addition and subtraction

### PR DESCRIPTION
**Pull request by jklmnn**

### CODE REVIEW

**Comment by senier** [comment]
The CI times out as the proofs take too long. Maybe passing `--info` to SPARK will produce some output to keep the CI going?

**Comment by senier** [comment]
We should also use `--steps` in favor of `--level` to make proofs more deterministic.

**Comment by jklmnn** [comment]
Adding `--report=all` to the proof (https://github.com/Componolit/ada-runtime/pull/52/commits/30286b4770a3405791089aeb95a1fba4c8e33896) makes it work in Travis. Also there's a problem on Genode that applications that use s-arit64 in a certain way do not compile due to a configuration error of the package. I wasn't able to provide a small reproducer. Simply using the package with arithmetic operations doesn't seem to trigger it. I still added a test on posix (https://github.com/Componolit/ada-runtime/pull/52/commits/9802bbb9900de6f3fdcc930dd59cdc91689cad21) but not on Genode. Still I was able to fix it (https://github.com/Componolit/ada-runtime/pull/52/commits/7a56641244194ea10a5773b697d6e657e09dbd34).

**Comment by senier** [comment]
The proof is not beautiful, but a proof is a proof ;-)

**Pull request merged**
